version: "3.7"

services:
  queries_challenge:
    image: postgres:12.10
    container_name: queries_challenge
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: challenge
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - queries_challenge
    depends_on: 
      - queries_challenge

volumes:
  pgdata:
    driver: local
